[package]
name = "ant_bin"
version = "0.1.0"
authors = ["Lukas"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ant_lib = { path = "../ant_lib" }
rand = "*"